apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-33j8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-33j8@sha256:76c365d8828483cc127aaa2f6c64b862fd4c3a8ce5f1c70fcf0ea429d0db65a5
        name: my-nodejs
        resources: {}
status: {}
